
name: openfoam-runtime

services:
  openfoam:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openfoam-runtime
    stdin_open: true
    tty: true
    volumes:
      - .:/workspace